### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by reszel** [giuliopanda/admin-form-pro#1]
“Detail Link: Makes the text clickable. Opens a popup with the details of the record. You can configure the details in the detailed view of the frontend.” 
That is exactly what I was looking for!

AKA: @bibeldans
Thank you for your patience!

**Comment by giuliopanda** [comment]
Hi, sorry to close your wordpress tickets, but as you saw wordpress administrators are very strict and this plugin is not having much success. Few people use it and it has only one rating.

To change the popup that appears on the detail link you can go to the "frontend" tab and at the bottom of the page, under "Detail View" you can change the view. 

If you select "Custom" next to "view type," you can enter html and short codes to create your own view. You can see the names of the variables by clicking on the "show shortcode variables" link below the editor.

Along with the documentation you will find tutorials I wrote to explain how it works, I hope they can help you.
